import * as fs from 'node:fs';
import * as path from 'node:path';

const tokensPath = path.resolve(__dirname, 'design-tokens.json');
const outputDir = path.resolve(__dirname, 'generated');

const tokens = JSON.parse(fs.readFileSync(tokensPath, 'utf-8'));

function resolveReference(ref: string): string {
  if (ref.startsWith('#')) return ref;

  const parts = ref.split('/');
  const [root, ...rest] = parts;

  if (root === 'lightMode' || root === 'darkMode') {
    const [color, shade] = rest;
    return tokens.colors[root]?.[color]?.[shade] ?? ref;
  }
  if (root === 'neutral') {
    return tokens.colors.neutral[rest[0]] ?? ref;
  }
  if (root === 'overlay') {
    const [color, shade] = rest;
    return tokens.colors.overlay?.[color]?.[shade] ?? ref;
  }
  return ref;
}

function resolveThemedVariables(themeMode: 'light' | 'dark') {
  const vars = tokens.colors.themedVariables[themeMode];
  const resolved: Record<string, Record<string, string>> = {};
  for (const category of Object.keys(vars)) {
    resolved[category] = {};
    for (const [key, value] of Object.entries(vars[category])) {
      resolved[category][key] = resolveReference(value as string);
    }
  }
  return resolved;
}

// --- Generate colorScales.js ---
function generateColorScales() {
  const { lightMode, darkMode } = tokens.colors;

  const lines: string[] = [];
  lines.push('// Auto-generated by generateThemeTokens.ts - DO NOT EDIT');
  lines.push('');

  for (const [name, scale] of Object.entries(lightMode)) {
    lines.push(`export const ${name} = ${JSON.stringify(scale, null, 2)};`);
    lines.push('');
  }

  lines.push('// Dark mode scales');
  for (const [name, scale] of Object.entries(darkMode)) {
    lines.push(`export const dark_${name} = ${JSON.stringify(scale, null, 2)};`);
    lines.push('');
  }

  return lines.join('\n');
}

// --- Generate paletteLight.js (DEPRECATED - paletteLight.js is now manually maintained) ---
function generatePaletteLight() {
  const lightVars = resolveThemedVariables('light');
  const { functional } = tokens.colors;
  const { lightMode } = tokens.colors;

  const palette = {
    primary: {
      main: functional['info-3'],
      light: functional['info-1'],
      dark: lightMode.blue['900'],
    },
    secondary: {
      main: lightMode.golden['500'],
      light: lightMode.golden['100'],
      dark: lightMode.golden['900'],
    },
    error: {
      main: functional['error-3'],
      light: functional['error-1'],
      dark: '#A83535',
    },
    warning: {
      main: functional['warning-3'],
      light: functional['warning-1'],
      dark: '#B8860B',
    },
    info: {
      main: functional['info-3'],
      light: functional['info-1'],
      dark: lightMode.blue['900'],
    },
    success: {
      main: functional['success-3'],
      light: functional['success-1'],
      dark: '#3D6B35',
    },
    text: {
      primary: lightVars.ink['gray-9'],
      secondary: lightVars.ink['gray-5'],
      disabled: lightVars.ink['gray-4'],
    },
    background: {
      default: lightVars.surface['gray-1'],
      paper: lightVars.surface['white'],
    },
    divider: lightVars.outline['gray-1'],
    action: {
      active: tokens.colors.overlay.black['200'],
      hover: tokens.colors.overlay.black['50'],
      hoverOpacity: 0.04,
      selected: tokens.colors.overlay.black['100'],
      selectedOpacity: 0.08,
      disabled: tokens.colors.overlay.black['200'],
      disabledBackground: tokens.colors.overlay.black['100'],
      disabledOpacity: 0.38,
      focus: tokens.colors.overlay.black['100'],
      focusOpacity: 0.12,
      activatedOpacity: 0.12,
    },
    grey: lightMode.gray,
  };

  const lines: string[] = [];
  lines.push('// Auto-generated by generateThemeTokens.ts - DO NOT EDIT');
  lines.push('');
  lines.push(`const paletteLight = ${JSON.stringify(palette, null, 2)};`);
  lines.push('');
  lines.push('export default paletteLight;');
  lines.push('');
  return lines.join('\n');
}

// --- Generate paletteDark.js ---
function generatePaletteDark() {
  const { darkMode } = tokens.colors;

  const palette = {
    primary: {
      main: darkMode.blue['400'],
      light: darkMode.blue['900'],
      dark: darkMode.blue['50'],
    },
    secondary: {
      main: darkMode.golden['500'],
      light: darkMode.golden['800'],
      dark: darkMode.golden['200'],
    },
    error: {
      main: '#E43838',
      light: '#361515',
      dark: '#901818',
    },
    warning: {
      main: '#E37D00',
      light: '#371E06',
      dark: '#603007',
    },
    info: {
      main: darkMode.blue['400'],
      light: darkMode.blue['900'],
      dark: darkMode.blue['50'],
    },
    success: {
      main: '#1BA964',
      light: '#0B2E1C',
      dark: '#035831',
    },
    text: {
      primary: '#F5F7FA',
      secondary: '#898E98',
      tertiary: '#898E98',
      disabled: '#5F636B',
      hint: '#898E98',
      highlight: '#038247',
    },
    background: {
      default: '#0F1011',
      paper: '#151515',
      subtle: '#151617',
      soft: '#1B1B1B',
    },
    divider: '#454545',
    action: {
      active: '#C6CAD2',
      hover: '#1B1B1B',
      hoverOpacity: 0.08,
      selected: '#1B1B1B',
      selectedOpacity: 0.16,
      disabled: '#5F636B',
      disabledBackground: '#2A2A2A',
      disabledOpacity: 0.38,
      focus: '#252627',
      focusOpacity: 0.12,
      activatedOpacity: 0.24,
    },
    grey: {
      50: '#F5F7FA',
      100: '#E1E4E8',
      200: '#C6CAD2',
      300: '#A7ADB7',
      400: '#898E98',
      500: '#6E737C',
      600: '#5F636B',
      700: '#454545',
      800: '#252627',
      900: '#151617',
    },
  };

  const lines: string[] = [];
  lines.push('// Auto-generated by generateThemeTokens.ts - DO NOT EDIT');
  lines.push('');
  lines.push(`const paletteDark = ${JSON.stringify(palette, null, 2)};`);
  lines.push('');
  lines.push('export default paletteDark;');
  lines.push('');
  return lines.join('\n');
}

// --- Generate shadows.js ---
function generateShadows() {
  const { shadows: s } = tokens;

  // Map 4 design-token levels to MUI's 25-element array:
  // 0: none, 1-4: small, 5-8: medium, 9-12: large, 13-24: xlarge
  const shadowArray: string[] = [
    'none',
    ...Array(4).fill(s.small),
    ...Array(4).fill(s.medium),
    ...Array(4).fill(s.large),
    ...Array(12).fill(s.xlarge),
  ];

  const lines: string[] = [];
  lines.push('// Auto-generated by generateThemeTokens.ts - DO NOT EDIT');
  lines.push('');
  lines.push(`const shadows = ${JSON.stringify(shadowArray, null, 2)};`);
  lines.push('');
  lines.push('export default shadows;');
  lines.push('');
  return lines.join('\n');
}

// --- Generate shape.js ---
function generateShape() {
  const { radius } = tokens;

  const lines: string[] = [];
  lines.push('// Auto-generated by generateThemeTokens.ts - DO NOT EDIT');
  lines.push('');
  lines.push(`const shape = {`);
  lines.push(`  borderRadius: ${radius['2']},`);
  lines.push(`};`);
  lines.push('');
  lines.push(`export const radius = ${JSON.stringify(radius, null, 2)};`);
  lines.push('');
  lines.push('export default shape;');
  lines.push('');
  return lines.join('\n');
}

// --- Generate size.js ---
function generateSize() {
  const { size } = tokens;

  const lines: string[] = [];
  lines.push('// Auto-generated by generateThemeTokens.ts - DO NOT EDIT');
  lines.push('');
  lines.push(`const size = ${JSON.stringify(size, null, 2)};`);
  lines.push('');
  lines.push('export default size;');
  lines.push('');
  return lines.join('\n');
}

// --- Generate extensions.js ---
function generateExtensions() {
  const { label, functional } = tokens.colors;

  const lines: string[] = [];
  lines.push('// Auto-generated by generateThemeTokens.ts - DO NOT EDIT');
  lines.push('');
  lines.push(`export const label = ${JSON.stringify(label, null, 2)};`);
  lines.push('');
  lines.push(`export const functional = ${JSON.stringify(functional, null, 2)};`);
  lines.push('');
  return lines.join('\n');
}

// --- Generate typography.js ---
function generateTypography() {
  const { typography } = tokens;

  const lines: string[] = [];
  lines.push('// Auto-generated by generateThemeTokens.ts - DO NOT EDIT');
  lines.push('');
  lines.push(`const typography = ${JSON.stringify(typography, null, 2)};`);
  lines.push('');
  lines.push('export default typography;');
  lines.push('');
  return lines.join('\n');
}

// --- Generate spacing.js ---
function generateSpacing() {
  const { spacing } = tokens;

  const lines: string[] = [];
  lines.push('// Auto-generated by generateThemeTokens.ts - DO NOT EDIT');
  lines.push('');
  lines.push(`const spacing = ${JSON.stringify(spacing, null, 2)};`);
  lines.push('');
  lines.push('export default spacing;');
  lines.push('');
  return lines.join('\n');
}

// --- Generate themedVariables.js ---
function generateThemedVariables() {
  const lightVars = resolveThemedVariables('light');
  const darkVars = resolveThemedVariables('dark');

  const lines: string[] = [];
  lines.push('// Auto-generated by generateThemeTokens.ts - DO NOT EDIT');
  lines.push('');
  lines.push(`export const lightThemedVariables = ${JSON.stringify(lightVars, null, 2)};`);
  lines.push('');
  lines.push(`export const darkThemedVariables = ${JSON.stringify(darkVars, null, 2)};`);
  lines.push('');
  return lines.join('\n');
}

// --- Write all files ---
function ensureDir(dir: string) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function main() {
  ensureDir(outputDir);

  const files: Record<string, string> = {
    'colorScales.js': generateColorScales(),
    'paletteDark.js': generatePaletteDark(),
    'shadows.js': generateShadows(),
    'shape.js': generateShape(),
    'size.js': generateSize(),
    'typography.js': generateTypography(),
    'spacing.js': generateSpacing(),
    'extensions.js': generateExtensions(),
    'themedVariables.js': generateThemedVariables(),
  };

  for (const [filename, content] of Object.entries(files)) {
    const filePath = path.join(outputDir, filename);
    fs.writeFileSync(filePath, content, 'utf-8');
    console.log(`  ✓ ${filename}`);
  }

  console.log(`\nGenerated ${Object.keys(files).length} files in ${outputDir}`);
}

main();
